version: "3.9"
services:
  dashboard:
    container_name: dashboard
    build:
      context: ./services/dashboard
      dockerfile: Dockerfile
      args:
        - VITE_CUSTOMERS_URL=http://localhost:8001/customers
        - VITE_ORDERS_URL=http://localhost:8002/orders
        - VITE_SUPPLIERS_URL=http://localhost:8003/suppliers
    ports:
      - 3000:80
      - 8001:8001
      - 8002:8002
      - 8003:8003
    links:
      - customers
      - orders
      - suppliers
    restart: always
    depends_on:
      - orders
    
  customers:
    container_name: customers
    build:
      context: ./services/customers
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    depends_on:
      - mongo
      - redis
    links:
      - mongo
      - redis
    
  suppliers:
    container_name: suppliers
    build:
      context: ./services/suppliers
      dockerfile: Dockerfile
    ports:
      - 3003:3003
    depends_on:
      - mongo
      - redis
    links:
      - mongo
      - redis

  orders:
    container_name: orders
    build:
      context: ./services/orders
      dockerfile: Dockerfile
    ports:
      - 3002:3002
    depends_on:
      - customers
      - suppliers
    links:
      - mongo
      - redis
      - customers
      - suppliers

  mongo:
    container_name: mongo
    image: mongo:5.0.11
    ports:
      - 27017:27017
    restart: always

  redis:
    container_name: redis
    image: redis:alpine3.16
    ports:
      - 6379:6379
    restart: always
  