version: "3.9"
services:
  dashboard:
    container_name: dashboard
    build:
      context: ./services/dashboard
      dockerfile: Dockerfile
      args:
        - VITE_CUSTOMERS_URL=http://localhost:8001/customers
        - VITE_ORDERS_URL=http://localhost:8002/orders
        - VITE_SUPPLIERS_URL=http://localhost:8003/suppliers
        - VITE_AUTH_URL=http://localhost:8004/users
        - VITE_ORDERS_WS_URL=ws://localhost:8002/ws
    ports:
      - 3000:80
      - 8001:8001
      - 8002:8002
      - 8003:8003
      - 8004:8004
    links:
      - customers
      - orders
      - suppliers
      - auth
    restart: always
    depends_on:
      - orders
      - auth
    
  customers:
    container_name: customers
    build:
      context: ./services/customers
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    depends_on:
      - mongo
      - redis
      - auth
    links:
      - mongo
      - redis
      - auth
    
  suppliers:
    container_name: suppliers
    build:
      context: ./services/suppliers
      dockerfile: Dockerfile
    ports:
      - 3003:3003
    depends_on:
      - mongo
      - redis
      - auth
    links:
      - mongo
      - redis
      - auth

  orders:
    container_name: orders
    build:
      context: ./services/orders
      dockerfile: Dockerfile
    ports:
      - 3002:3002
    depends_on:
      - customers
      - suppliers
      - auth
    links:
      - mongo
      - redis
      - customers
      - suppliers
      - auth

  auth:
    container_name: auth
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    ports:
      - 3004:3004
    depends_on:
      - mongo
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo:5.0.11
    ports:
      - 27017:27017
    restart: always
    volumes:
      - ./services/mongo:/data/db

  redis:
    container_name: redis
    image: redis:alpine3.16
    ports:
      - 6379:6379
    restart: always
  