basePath: /
definitions:
  data.Customer:
    properties:
      created_at:
        type: string
      id:
        type: string
      name:
        type: string
      updated_at:
        type: string
    type: object
  main.Response:
    properties:
      message:
        type: string
    type: object
host: localhost:8001
info:
  contact:
    email: omarbelghaouti@gmail.com
    name: Omar Belghaouti
  description: pdash customers service
  title: pdash customers service
  version: "1.0"
paths:
  /customers:
    get:
      consumes:
      - application/json
      description: Get all Customers
      operationId: get-customers
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/data.Customer'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/main.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/main.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.Response'
      summary: Get all Customers
    post:
      consumes:
      - application/json
      description: Create a new Customer
      operationId: create-customer
      parameters:
      - description: Customer
        in: body
        name: customer
        required: true
        schema:
          $ref: '#/definitions/data.Customer'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/main.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/main.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.Response'
      summary: Create a new Customer
  /customers/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a Customer by ID
      operationId: delete-customer-by-id
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/main.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/main.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.Response'
      summary: Delete a Customer by ID
    get:
      consumes:
      - application/json
      description: Get a Customer by ID
      operationId: get-customer-by-id
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/data.Customer'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/main.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/main.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.Response'
      summary: Get a Customer by ID
    put:
      consumes:
      - application/json
      description: Update a Customer by ID
      operationId: update-customer-by-id
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      - description: Customer
        in: body
        name: customer
        required: true
        schema:
          $ref: '#/definitions/data.Customer'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/data.Customer'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/main.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/main.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.Response'
      summary: Update a Customer by ID
swagger: "2.0"
